### ISSUE TITLE
Postcodes with a single inner number are reported as valid

### ISSUE THREAD

**Issue by jFransham** [ideal-postcodes/postcode#7]
Example: `EH1 JS`

All postcodes with the format `\w{2}\d\w{2}` are currently accepted as valid.

@billinghamj 

EDIT: the one that was accepted was `EH 1JS`, whoops

**Comment by cblanc** [comment]
It seems `EH1 JS` is not valid but `EH1JS` is. Not sure if `\w{2}\d\w{2}` is entirely right since `\w` also includes underscore and numbers but I think I get your meaning

I think this is definitely a false positive we're able to eliminate with some tighter regex'ing

I made a first pass at it here by amending the way outward codes are handled: https://github.com/ideal-postcodes/postcode.js/pull/8

@billinghamj would be great if you have time to take a look (-:

**Comment by billinghamj** [comment]
Will take a look when I get a chance. We're just implementing this in one of services, and Jack noticed the issue! :)

**Comment by billinghamj** [comment]
@jFransham This can be closed. Was fixed by #8 (v0.2.5 on npm).
